# Generated by Django 4.1.7 on 2023-07-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirement_recieved',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='round1',
            name='screenshot_shared',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='round2',
            name='screenshot_shared',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='round3',
            name='screenshot_shared',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
