# Generated by Django 4.1.7 on 2023-07-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_requirement_recieved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requirement_recieved',
        ),
    ]
