# Generated by Django 4.1.7 on 2023-07-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_requirement_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round1',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round2',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
        migrations.AddField(
            model_name='round3',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bde_user'),
        ),
    ]
